name: CI Update Jekyll

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: dataherb-flora
      - name: update jekyll site
        uses: actions/checkout@v2
        with:
          repository: DataHerb/dataherb.github.io
          path: dataherb.github.io
      - name: Get current directory and files
        run: |
          pwd
          ls
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install Python Requirements
        working-directory: ./dataherb-flora
        run: pip install -r requirements.txt
      - name: Create flora.json
        working-directory: ./dataherb-flora
        run: |
          BUILD_FOLDER=build
          JEKYLL_MD_FOLDER=_datasets
          echo "Creating folder $BUILD_FOLDER"
          mkdir -p $BUILD_FOLDER
          mkdir -p $BUILD_FOLDER/$JEKYLL_MD_FOLDER
          echo "Creating flora metadata."
          python agg/agg.py
          echo "Creating .nojekyll"
          touch $BUILD_FOLDER/.nojekyll
          echo "All files in $BUILD_FOLDER"
          ls -alht $BUILD_FOLDER
          pwd
          ls -alht $BUILD_FOLDER/$JEKYLL_MD_FOLDER
      - name: Update Jekyll dataset files
        run: |
          BUILD_FOLDER=build
          JEKYLL_MD_FOLDER=_datasets
          cp dataherb-flora/$BUILD_FOLDER/$JEKYLL_MD_FOLDER/* dataherb.github.io/_datasets/
          cd dataherb.github.io
          pwd
          ls
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add _datasets
          git commit -am "Update Datasets"
          git status
      - name: Push changes to jekyll site
        uses: ad-m/github-push-action@master
        with:
          repository: dataherb.github.io
          directory: dataherb.github.io
          github_token: ${{ secrets.ACCESS_TOKEN }}
