name: CI Update Jekyll

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dataherb-flora
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          path: dataherb-flora
      - name: Checkout dataherb-metadata-aggregator
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: DataHerb/dataherb-metadata-aggregator
          path: dataherb-metadata-aggregator
      - name: Checkout dataherb.github.io
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: DataHerb/dataherb.github.io
          path: dataherb.github.io
      - name: Get current directory and files
        run: |
          pwd
          ls
      - name: Copy Aggregator to flora repo
        run: |
          mkdir -p dataherb-flora/agg
          cp dataherb-metadata-aggregator/agg/* dataherb-flora/agg
          cp dataherb-metadata-aggregator/requirements.txt dataherb-flora/requirements.txt
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install Python Requirements
        working-directory: ./dataherb-flora
        run: pip install -r requirements.txt
      - name: Create flora.json
        working-directory: ./dataherb-flora
        run: |
          BUILD_FOLDER=build
          JEKYLL_MD_FOLDER=_flora
          echo "Creating folder $BUILD_FOLDER"
          mkdir -p $BUILD_FOLDER
          mkdir -p $BUILD_FOLDER/$JEKYLL_MD_FOLDER
          echo "Creating flora metadata."
          python agg/agg.py
          echo "Creating .nojekyll"
          touch $BUILD_FOLDER/.nojekyll
          echo "All files in $BUILD_FOLDER"
          ls -alht $BUILD_FOLDER
          pwd
          ls -alht $BUILD_FOLDER/$JEKYLL_MD_FOLDER
      - name: Update Jekyll flora files
        run: |
          BUILD_FOLDER=build
          JEKYLL_MD_FOLDER=_flora
          cp dataherb-flora/$BUILD_FOLDER/$JEKYLL_MD_FOLDER/* dataherb.github.io/$JEKYLL_MD_FOLDER/
          cd dataherb.github.io
          pwd
          ls
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add _flora
          git commit -m "Update Datasets" || echo "Nothing to update"
          git status
      - name: Push changes to jekyll site
        uses: ad-m/github-push-action@master
        with:
          repository: DataHerb/dataherb.github.io
          directory: dataherb.github.io
          github_token: ${{ secrets.ACCESS_TOKEN }}
